#spring.application.name=ShoppingMall
#server.port=80
#
# #spring.datasource.url=jdbc:mysql://db-lpeqn-kr.vpc-pub-cdb.ntruss.com:3306/shopping_mall?serverTimezone=Asia/Seoul
##spring.datasource.username=mini_ddl
## spring.datasource.password=bitcamp123!@#
## spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
#
#spring.datasource.url=jdbc:mysql://db-lsa9l-kr.vpc-pub-cdb.ntruss.com:3306/Mini_Shoppingmall?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=mini
#spring.datasource.password=1q2w3e4r!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## mybatis mapper ????
## classpath = src/main/resources
#mybatis.mapper-locations=classpath:/mapper/**/*.xml
#
#spring.thymeleaf.prefix=classpath:/templates
#spring.thymeleaf.suffix=.html
#
#spring.session.store-type=jdbc
#
